spring.application.name=stegano
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.web.resources.static-locations=classpath:/static/
server.port=${PORT:8080}
